apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: py-internal-quay
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: py-internal-quay 
  name: py-internal-quay
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: py-internal-quay
    weight: 100 
