apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: py-internal-quay
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: py-internal-quay 
  name: py-internal-quay
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: py-internal-quay 
